server:
  port: 80

spring:
  application:
    name: demo-service2 #cloud-consumer-order
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        server-name: ${spring.application.name}