server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  #consul服务注册地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        server-name: ${spring.application.name}